#============================================================================
#
# simple project makefile (just a main file)
#
# (c) Wouter van Ooijen (wouter@voti.nl) 2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at 
# http://www.boost.org/LICENSE_1_0.txt) 
#
#============================================================================

# source files in this project (main.* is automatically assumed)
SOURCES := MPU9250.cpp

# header files in this project
HEADERS := MPU9250.hpp MPU9250_defines.hpp